### PR TITLE
caja-file: fix yesterday/today informal date bug

### LINKED ISSUE #1621: Caja timestam wrong
#### Expected behaviour
Files in directories have correct date modified stamp.

#### Actual behaviour
Files modified yesterday and closed yesterday stamped as (Date modified) today.

#### Steps to reproduce the behaviour
Create text document and save at 4 pm yesterday
View file list in Caja browser at 9 am today.
DATE MODIFIED is 4 pm today - 7 hours from now

#### MATE general version
1.24.0

#### Package version
1.24.0
caja_wonk

#### Linux Distribution
Mint 20.2

### PR DESCRIPTION
**Pull request by basicmaster**
If informal date format is used, the yesterday/today ranges of 48/24 hours apply to the end of the current day, not to the current instant.

Fixes a regression introduced by 476f56a25be636970b336d525a7766b6d1eb3fff. Fixes #1621.

### CODE REVIEW

**Comment by basicmaster** [comment]
Files in a folder, all from yesterday, accessed now (2023-04-15 at noon):
grafik

Caja without bugfix:
grafik

Caja with bugfix:
grafik

**Comment by lukefromdc** [comment]
I really do not know how to test this for function.
Using this date format here:

**Comment by basicmaster** [comment]
The last date format option in caja's settings is the one that is called "informal date format" in the code:
grafik

In general it uses the full form of the day of the week, not the abbreviated one. For files that have been modified today or yesterday, this format replaces day of week and date in the displayed modified date by the words "today" or "yesterday".

In this particular case, the patch makes a difference for a file that was created yesterday but is not older than 24 hours. The same applies to a file that was created two days ago but is not older than 48 hours. So for testing you would need to create such files e.g. using `touch -t`.

**Comment by lukefromdc** [comment]
It would be best if another team member could test this first, as I really can't wrap my head around this and never use that format

**Comment by raveit65** [comment]
I can reproduce the issue and i will test the fix.

File: libcaja-private/caja-file.c [hunk 1]
```diff
@@ -4866,9 +4866,15 @@ caja_file_fit_date_as_string (CajaFile *file,
 	}
 
 	today = g_date_time_new_now_local ();
-	file_date_age = g_date_time_difference (today, date_time);
+	end_of_today = g_date_time_add_full(today, 0, 0, 1,
+			-1 * g_date_time_get_hour(today),
+			-1 * g_date_time_get_minute(today),
+			-1.0 * g_date_time_get_seconds(today));
 	g_date_time_unref (today);
```
Comment (raveit65) [inline libcaja-private/caja-file.c:4873]: Formatting issue. Can you start line 4870-4872 after the openning bracket from line 4869
Also a blank before brackets are missing missing.

Comment (basicmaster) [reply libcaja-private/caja-file.c:4873]: I just fixed the formatting as requested and replaced the change commit with a fixed version.

Comment (raveit65) [reply libcaja-private/caja-file.c:4873]: Really?
Screenshot 2023-05-05 at 18-05-25 caja-file fix yesterday_today informal date bug by basicmaster · Pull Request #1710 · mate-desktop_caja

I do not get why people do have so much problems to work with tabs.
Personal i don't use tabs in code for myself....so i never run in that problems :-)

Comment (basicmaster) [reply libcaja-private/caja-file.c:4873]: Usually I try to align to the existing code as much as possible. As the code already uses tabs, I also used tabs for indentation. 

I increased the indent of lines 4870 to 4872 so that the text start is horizontally to the right of the opening bracket in line 4869....so what I am still missing here? :-)

Comment (raveit65) [reply libcaja-private/caja-file.c:4873]: Perfect , Danke schön :)

**Review by lukefromdc — APPROVED** [review]
Again, I cannot easily wrap my head around this date issue and would need files made at special time to attempt a function test, but this did not create any problems on my system on a test build and run (via sudo caja, which opens a new instance of caja not just a new window) of the built binary over my normal installation. No issues came up with the date format I am using (which I don't think I have ever changed.)

**Review by raveit65 — APPROVED** [review]
LGTM,
does what it promised and fixes the date format.
